/*
 * Class that is a GUI window used to change a users password.
 * The class requires the user to know the old password for him/her to be
 * able to change it to a new one.
 */
package GUI;

import BLL.MyBooksModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Niels, Dennis & Alex
 */
public class ChangeAPassword extends javax.swing.JDialog
{

    /**
     * Variables
     */
    private String newPassword = "";
    private String oldPassword;

    /**
     * Constructor Creates new form ChangeAPassword
     */
    public ChangeAPassword(MyBooksModel model, java.awt.Frame parent, boolean modal, String oldPassword)
    {
        super(parent, modal);
        initComponents();
        this.setTitle("MyBooks - Change Password");
        this.oldPassword = oldPassword;
    }

    /**
     * @return the newPassword
     */
    public String getNewPassword()
    {
        return newPassword;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        passwordMainPnl = new javax.swing.JPanel();
        oldPassLbl = new javax.swing.JLabel();
        newPassLbl = new javax.swing.JLabel();
        oldPass = new javax.swing.JTextField();
        newPass = new javax.swing.JTextField();
        okPasswordBtn = new javax.swing.JButton();
        passwordCancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        oldPassLbl.setText("Old Password:");

        newPassLbl.setText("New Password:");

        oldPass.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                oldPassActionPerformed(evt);
            }
        });

        okPasswordBtn.setText("Ok");
        okPasswordBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okPasswordBtnActionPerformed(evt);
            }
        });

        passwordCancelBtn.setText("Cancel");
        passwordCancelBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                passwordCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout passwordMainPnlLayout = new javax.swing.GroupLayout(passwordMainPnl);
        passwordMainPnl.setLayout(passwordMainPnlLayout);
        passwordMainPnlLayout.setHorizontalGroup(
            passwordMainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordMainPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passwordMainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oldPassLbl)
                    .addComponent(newPassLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(passwordMainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordMainPnlLayout.createSequentialGroup()
                        .addComponent(okPasswordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwordCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        passwordMainPnlLayout.setVerticalGroup(
            passwordMainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordMainPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passwordMainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPassLbl)
                    .addComponent(oldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(passwordMainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPassLbl)
                    .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(passwordMainPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okPasswordBtn)
                    .addComponent(passwordCancelBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(passwordMainPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passwordMainPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Button method. Verifies that the user knows the old password, if the user
     * does, the password is changed to the new password. The new password field
     * cannot be empty.
     *
     * @param evt
     */
    private void okPasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okPasswordBtnActionPerformed
        String passnum = newPass.getText();
        if (passnum.matches(".*\\d+.*")){
        String old = oldPass.getText();
        String neew = newPass.getText();
        if (old.equals(oldPassword))
        {
            if (!neew.isEmpty())
            {
                newPassword = neew;
                dispose();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Can't change password", "Error", JOptionPane.ERROR_MESSAGE);
        }}else{
            JOptionPane.showMessageDialog(this, "Password must contain a digit", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_okPasswordBtnActionPerformed

    /**
     * Button method that closes the new password window, without making any changes.
     * @param evt 
     */
    private void passwordCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordCancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_passwordCancelBtnActionPerformed

    private void oldPassActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_oldPassActionPerformed
    {//GEN-HEADEREND:event_oldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldPassActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField newPass;
    private javax.swing.JLabel newPassLbl;
    private javax.swing.JButton okPasswordBtn;
    private javax.swing.JTextField oldPass;
    private javax.swing.JLabel oldPassLbl;
    private javax.swing.JButton passwordCancelBtn;
    private javax.swing.JPanel passwordMainPnl;
    // End of variables declaration//GEN-END:variables

}
